import handle from "hono-remix-adapter/cloudflare-pages";
import { getLoadContext } from "../load-context";
import server from "../server";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

export const onRequest = handle(build, server, { getLoadContext });
