#!/bin/bash

###
# kysely-codegen requires a .env file that has `DATABASE_URL` to be present in the project root.
# This script generates a .env file in the project root from any file, e.g.) ".dev.vars".
###

# Check if a filename was provided
if [ -z "$1" ]; then
    echo "Error: Please provide a file name"
    echo "Usage: ./generate-env.sh <filename>"
    exit 1
fi

# Check if the input file exists
if [ ! -f "$1" ]; then
    echo "Error: File $1 does not exist"
    exit 1
fi

# Read SUPABASE_URI from the input file
SUPABASE_URI=$(grep "^SUPABASE_URI=" "$1" | cut -d '=' -f2- | tr -d '"')

# Check if SUPABASE_URI was found
if [ -z "$SUPABASE_URI" ]; then
    echo "Error: SUPABASE_URI not found in $1"
    exit 1
fi

# Convert port 6543 to 5432
DATABASE_URL="${SUPABASE_URI//:6543/:5432}"

# Check if .env already exists
if [ -f ".env" ]; then
    echo "Warning: .env file already exists. Skipping."
    exit 0
fi

# Create .env file with DATABASE_URL
echo "# This file is generated by generate-dotenv.sh for kysely-codegen" > .env
echo "DATABASE_URL=\"$DATABASE_URL\"" >> .env

echo "Successfully created .env file with DATABASE_URL"